// web-cash/components/Header.vue
<script setup lang="ts">
/* Define properties. */
// https://vuejs.org/guide/components/props.html#props-declaration
const props = defineProps({
    data: {
        type: [Object],
    },
})

/* Initialize stores. */
import { useSystemStore } from '@/stores/system'
const System = useSystemStore()

const emits = defineEmits(['toggleMenu'])

const displayQuote = computed(() => {
    if (!System.avasUsd) {
        return {
            primary: '$0.00',
            secondary: '0000',
        }
    }

    return {
        primary: '$' + System.avasUsd.toString().split('.')[0] + '.' + System.avasUsd.toString().split('.')[1].slice(0, 2),
        secondary: System.avasUsd.toString().split('.')[1].slice(2, 6),
    }
})

const toggleMenu = () => {
    emits('toggleMenu')
}

onMounted(() => {
    // TODO
})

// onBeforeUnmount(() => {
//     console.log('Before Unmount!')
//     // Now is the time to perform all cleanup operations.
// })

</script>

<template>
    <header class="absolute inset-x-0 sticky top-0 z-20 bg-white border-b border-gray-100 bg-opacity-90 backdrop-blur-md">
        <nav class="mx-auto flex max-w-7xl items-center justify-between gap-8 px-6 py-3 lg:px-8" aria-label="Global">
            <div class="flex lg:flex-1">
                <NuxtLink to="/" class="-m-1.5 p-1.5">
                    <span class="sr-only">Nxy Cash</span>
                    <img class="w-12 h-auto" src="~/assets/logo.png" alt="" />
                </NuxtLink>
            </div>

            <div class="flex lg:hidden items-center gap-6 sm:gap-8">
                <ClientOnly>
                    <NuxtLink to="/markets" class="flex flex-row items-end gap-1 text-4xl text-rose-500 font-medium">
                        <div class="flex flex-row items-start">
                            <sup class="mt-2 text-xs text-rose-300">mNXY/USD</sup>
                            {{displayQuote.primary}}
                        </div>

                        <span class="text-lg text-rose-300">
                            {{displayQuote.secondary}}
                        </span>
                    </NuxtLink>
                </ClientOnly>

                <button @click="toggleMenu" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-12 h-auto" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </button>
            </div>

            <div class="hidden lg:flex lg:gap-x-12">
                <NuxtLink to="/mining" class="text-xl font-semibold leading-6 text-gray-900">
                    Mining
                </NuxtLink>

                <NuxtLink to="https://nxy.app" target="_blank" class="text-xl font-semibold leading-6 text-gray-900">
                    Download
                </NuxtLink>

                <NuxtLink to="/token" class="text-xl font-semibold leading-6 text-gray-900">
                    $NXY
                </NuxtLink>

                <NuxtLink to="/whitepaper" class="text-xl font-semibold leading-6 text-gray-900">
                    Whitepaper
                </NuxtLink>

                <NuxtLink to="/help" class="text-xl font-semibold leading-6 text-gray-900">
                    Help
                </NuxtLink>
            </div>

            <div class="hidden lg:flex lg:flex-1 lg:justify-end items-center gap-10">
                <ClientOnly>
                    <NuxtLink to="/markets" class="flex flex-row items-end gap-1 text-4xl text-rose-500 font-medium">
                        <div class="flex flex-row items-start">
                            <sup class="mt-2 text-xs text-rose-300">mNXY/USD</sup>
                            {{displayQuote.primary}}
                        </div>

                        <span class="text-lg text-rose-300">
                            {{displayQuote.secondary}}
                        </span>
                    </NuxtLink>
                </ClientOnly>

                <button @click="toggleMenu" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-12 h-auto" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </button>
            </div>
        </nav>
    </header>
</template>

// web/src/components/Header.jsx
import Link from 'next/link'
import { Popover } from '@headlessui/react'
import { AnimatePresence, motion } from 'framer-motion'

import { Button } from '@/components/Button'
import { Container } from '@/components/Container'
import { Logo } from '@/components/Logo'
import { NavLinks } from '@/components/NavLinks'

function MenuIcon(props) {
    return (
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" {...props}>
            <path
                d="M5 6h14M5 18h14M5 12h14"
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
            />
        </svg>
    )
}

function ChevronUpIcon(props) {
    return (
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" {...props}>
            <path
                d="M17 14l-5-5-5 5"
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
            />
        </svg>
    )
}

function MobileNavLink({ children, ...props }) {
    return (
        <Popover.Button
            as={Link}
            className="block text-xl leading-7 tracking-tight text-gray-700"
            {...props}
        >
            {children}
        </Popover.Button>
    )
}

export function Header() {
    return (
        <header>
            <nav>
                <Container className="relative z-50 flex justify-between py-8">
                    <div className="relative z-10 flex items-center gap-16">
                        <Link href="/" aria-label="Home">
                            <Logo className="h-10 w-auto" />
                        </Link>

                        <div className="hidden lg:flex lg:gap-10">
                            <NavLinks />
                        </div>
                    </div>

                    <div className="flex items-center gap-6">
                        <Popover className="lg:hidden">
                            {({ open }) => (
                                <>
                                    <Popover.Button
                                        className="relative z-10 -m-2 inline-flex items-center rounded-lg stroke-gray-900 p-2 hover:bg-gray-200/50 hover:stroke-gray-600 active:stroke-gray-900 [&:not(:focus-visible)]:focus:outline-none"
                                        aria-label="Toggle site navigation"
                                    >
                                        {({ open }) =>
                                            open ? (
                                                <ChevronUpIcon className="h-10 w-10" />
                                            ) : (
                                                <MenuIcon className="h-10 w-10" />
                                            )
                                        }
                                    </Popover.Button>

                                    <AnimatePresence initial={false}>
                                        {open && (
                                            <>
                                                <Popover.Overlay
                                                    static
                                                    as={motion.div}
                                                    initial={{ opacity: 0 }}
                                                    animate={{ opacity: 1 }}
                                                    exit={{ opacity: 0 }}
                                                    className="fixed inset-0 z-0 bg-gray-300/60 backdrop-blur"
                                                />

                                                <Popover.Panel
                                                    static
                                                    as={motion.div}
                                                    initial={{ opacity: 0, y: -32 }}
                                                    animate={{ opacity: 1, y: 0 }}
                                                    exit={{
                                                        opacity: 0,
                                                        y: -32,
                                                        transition: { duration: 0.2 },
                                                    }}
                                                    className="absolute inset-x-0 top-0 z-0 origin-top rounded-b-2xl bg-gray-50 px-6 pb-6 pt-32 shadow-2xl shadow-gray-900/20"
                                                >
                                                    <div className="space-y-4">
                                                        <MobileNavLink href="#features">
                                                            Features
                                                        </MobileNavLink>

                                                        <MobileNavLink href="#reviews">
                                                            Reviews
                                                        </MobileNavLink>

                                                        <MobileNavLink href="#bundles">
                                                            Noob Bundles
                                                        </MobileNavLink>

                                                        <MobileNavLink href="#faqs">
                                                            FAQs
                                                        </MobileNavLink>
                                                    </div>

                                                    <div className="mt-8 flex flex-col gap-4">
                                                        <Button href="https://avas.cash" target="_blank" variant="outline" className="py-4 text-[1.4em]">
                                                            mNXY/USD $0.01
                                                        </Button>

                                                        <Button href="https://avas.cash/mining" target="_blank" className="py-4 text-[1.8em]">
                                                            Start Mining
                                                        </Button>
                                                    </div>
                                                </Popover.Panel>
                                            </>
                                        )}
                                    </AnimatePresence>
                                </>
                            )}
                        </Popover>

                        <Button href="https://nxy.cash" target="_blank" variant="outline" className="hidden lg:block text-lg font-light tracking-wider">
                            mNXY/USD $0.01
                        </Button>

                        <Button href="https://avas.cash/mining" target="_blank" className="hidden lg:block text-lg font-medium tracking-widest">
                            Start Mining
                        </Button>
                    </div>
                </Container>
            </nav>
        </header>
    )
}
